version: '3'
services:
  influxdb:
    image: influxdb
    ports:
      - 8083:8083
      - 8086:8086
    hostname: influxdb
    volumes:
      - "$PWD/influxdb:/var/lib/influxdb"
      - "$PWD/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
      # - "$PWD/types.db:/usr/share/collectd/types.db:ro"

  grafana:
    image: grafana/grafana
    environment:
      - "GF_SERVER_ROOT_URL=http://127.0.0.1"
      # - "GF_SECURITY_ADMIN_PASSWORD=secret"
      # - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
    ports:
      - 3000:3000
    links:
      - influxdb
    volumes:
      - $PWD/grafana:/var/lib/grafana
      - $PWD/grafana.ini:/etc/grafana/grafana.ini

  telegraf:
    image: telegraf
    privileged: true
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    links:
      - influxdb
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
